name: raxa_hosted
version: 0.0.1
description: >
  Home steering
author: Rasmus Eneman <rasmus@eneman.eu>
#homepage: https://www.example.com
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: '>=0.10.0 <0.11.0'
  uix: any
  sass: '>=0.4.0 <0.5.0'
  script_inliner: '>=1.0.0 <2.0.0'
transformers:
- script_inliner
- sass
#    style: compressed
